/**
 * THIS FILE IS AUTO-GENERATED BY scripts/generate-env.js
 * DO NOT EDIT MANUALLY. Update .env.development or deployment environment variables.
 */
export const ENV = {
  production: false,
  apiUrl: 'https://eatupapi-publisher.onrender.com/api/v1',
  locationId: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'
};
