const fs = require('fs');
const path = require('path');

function generateEnvFile(envFilePath, outputFilePath) {
  let envContent = '';
  try {
    envContent = fs.readFileSync(path.resolve(__dirname, '..', envFilePath), 'utf8');
  } catch (err) {
    console.warn(`Warning: Could not read ${envFilePath}. Ensure it exists.`);
    return;
  }

  const envVars = envContent.split('\n').reduce((acc, line) => {
    const match = line.match(/^([^=]+)=(.*)$/);
    if (match) {
      acc[match[1].trim()] = match[2].trim();
    }
    return acc;
  }, {});

  const fileContent = `/**
 * THIS FILE IS AUTO-GENERATED BY scripts/generate-env.js
 * DO NOT EDIT MANUALLY. Update .env.development at repository root.
 */
export const ENV = {
  production: false,
  apiUrl: '${envVars.API_URL || '/api/v1'}',
  userToken: '${envVars.USER_TOKEN || ''}',
  locationId: '${envVars.LOCATION_ID || ''}'
};
`;

  const dir = path.dirname(outputFilePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(outputFilePath, fileContent, 'utf8');
  console.log(`Generated ${outputFilePath} from ${envFilePath}`);
}

const outputPath = path.resolve(__dirname, '../src/app/core/config/env.config.ts');

// Generate the local front-end runtime config from .env.development
generateEnvFile('.env.development', outputPath);
