const fs = require('fs');
const path = require('path');

function readEnvFile(envFilePath) {
  try {
    const envContent = fs.readFileSync(path.resolve(__dirname, '..', envFilePath), 'utf8');

    return envContent.split('\n').reduce((acc, line) => {
      const trimmed = line.trim();

      if (!trimmed || trimmed.startsWith('#')) {
        return acc;
      }

      const match = trimmed.match(/^([^=]+)=(.*)$/);

      if (match) {
        acc[match[1].trim()] = match[2].trim();
      }

      return acc;
    }, {});
  } catch (err) {
    console.warn(`Warning: Could not read ${envFilePath}. Falling back to process.env.`);
    return {};
  }
}

function generateEnvFile(envFilePath, outputFilePath) {
  const envVarsFromFile = readEnvFile(envFilePath);

  const apiUrl =
    process.env.API_URL ||
    envVarsFromFile.API_URL ||
    '/api/v1';

  const locationId =
    process.env.LOCATION_ID ||
    envVarsFromFile.LOCATION_ID ||
    '';

  const fileContent = `/**
 * THIS FILE IS AUTO-GENERATED BY scripts/generate-env.js
 * DO NOT EDIT MANUALLY. Update .env.development or deployment environment variables.
 */
export const ENV = {
  production: false,
  apiUrl: '${apiUrl}',
  locationId: '${locationId}'
};
`;

  const dir = path.dirname(outputFilePath);

  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(outputFilePath, fileContent, 'utf8');
  console.log(`Generated ${outputFilePath}`);
  console.log(`API_URL=${apiUrl}`);
  console.log(`LOCATION_ID=${locationId}`);
}

const outputPath = path.resolve(__dirname, '../src/app/core/config/env.config.ts');

generateEnvFile('.env.development', outputPath);